export {default as Navbar} from './Navbar';
export {default as VideoDemo} from './VideoDemo';
export {default as HowItWorks}  from './HowItWorks';
export {default as WhereWeAreHeaded}  from './WhereWeAreHeaded';
export {default as PeerComparison}  from './PeerComparison';
export {default as FAQ}  from './FAQ';
export {default as Hero}  from './Hero';
export {default as Features}  from './Features';
export {default as Footer}  from './Footer';